changelog:
  categories:
    - title: 🚀 Features
      labels: [feat]
    - title: 🐛 Fixes
      labels: [fix]
    - title: 📚 Docs
      labels: [docs]
    - title: 🧪 Tests
      labels: [test]
    - title: 🔧 Chore
      labels: [chore]
    - title: Other changes
      labels: ["*"]
